### ISSUE TITLE
font-awesome字体包里面并没有 “fontawesome-webfont.ttf”

### ISSUE THREAD

**Issue by inix** [abczdefg/weapp-font-awesome#1]
下载fontawesome 版本 5.0.6解压之后 fontawesome-free-5.0.6，并没有 fontawesome-webfont.ttf 这个文件

**Comment by abczdefg** [comment]
@inix 这个小东西是一年前搞的了，那时候用的是 4.6.3 吧。刚刚看了一下版本5+似乎变了很多，没有使用过，但在github上还是能找到ttf文件的 
https://github.com/FortAwesome/Font-Awesome/tree/master/web-fonts-with-css/webfonts

**Comment by YxgHx** [comment]
大神好，我用了你的方法，在电脑开发者工具中可以显示出fontawesome图标，但在手机中就无法显示了。。。想请教下你有没有遇到这样的问题，然后就是如何解决的呢。https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=1662013712&docid=0004e8a4dd4ed089e9b60127d53c00
我在微信开发者社区也留了这个问题，然后附了图片
谢谢！

**Comment by abczdefg** [comment]
@YxgHx 我才不是大神。。也是看着别人的文章搞出来的，一年多没碰过小程序了。好像当时也没在手机上测试过，电脑上看到效果就传上来了。。
